### ISSUE TITLE
 Error: type object 'ExternalIdType' has no attribute 'XAPI'

### ISSUE THREAD

**Issue by Ian2012** [openedx/event-routing-backends#296]
## Description

After an upgrade to 5.3.0, this error happened (with some events)

```bash
2023-05-12 18:50:22,671 ERROR 45 [event_routing_backends.processors.mixins.base_transformer_processor] [user None] [ip None] base_transformer_processor.py:65 - There was an error while trying to transform event "edx.course.grade.passed.first_time" using XApiProcessor processor. Error: type object 'ExternalIdType' has no attribute 'XAPI'
Traceback (most recent call last):
  File "/openedx/venv/lib/python3.8/site-packages/event_routing_backends/processors/mixins/base_transformer_processor.py", line 58, in transform_event
    transformed_event = self.get_transformed_event(event)
  File "/openedx/venv/lib/python3.8/site-packages/event_routing_backends/processors/mixins/base_transformer_processor.py", line 100, in get_transformed_event
    return self.registry.get_transformer(event).transform()
  File "/openedx/venv/lib/python3.8/site-packages/event_routing_backends/processors/xapi/transformer.py", line 45, in transform
    transformed_props = super().transform()
  File "/openedx/venv/lib/python3.8/site-packages/event_routing_backends/processors/mixins/base_transformer.py", line 97, in transform
    self.base_transform()
  File "/openedx/venv/lib/python3.8/site-packages/event_routing_backends/processors/xapi/transformer.py", line 53, in base_transform
    actor = self.get_actor()
  File "/openedx/venv/lib/python3.8/site-packages/event_routing_backends/processors/xapi/transformer.py", line 82, in get_actor
    user_uuid = get_anonymous_user_id(self.extract_username_or_userid(), 'XAPI')
  File "/openedx/venv/lib/python3.8/site-packages/event_routing_backends/helpers.py", line 66, in get_anonymous_user_id
    type_name = getattr(ExternalIdType, external_type)
AttributeError: type object 'ExternalIdType' has no attribute 'XAPI'
2023-05-12 18:50:22,678 ERROR 45 [eventtracking.backends.routing] [user None] [ip None] routing.py:146 - Unable to send edx event "edx.course.grade.passed.first_time" to backend: xapi
Traceback (most recent call last):
  File "/openedx/venv/lib/python3.8/site-packages/eventtracking/backends/routing.py", line 137, in send_to_backends
    backend.send(event)
  File "/openedx/venv/lib/python3.8/site-packages/event_routing_backends/backends/events_router.py", line 55, in send
    processed_event = self.process_event(event)
  File "/openedx/venv/lib/python3.8/site-packages/event_routing_backends/backends/events_router.py", line 131, in process_event
    event = processor(event)
  File "/openedx/venv/lib/python3.8/site-packages/event_routing_backends/processors/mixins/base_transformer_processor.py", line 35, in __call__
    transformed_event = self.transform_event(event)
  File "/openedx/venv/lib/python3.8/site-packages/event_routing_backends/processors/xapi/transformer_processor.py", line 44, in transform_event
    transformed_event = super().transform_event(event)
  File "/openedx/venv/lib/python3.8/site-packages/event_routing_backends/processors/mixins/base_transformer_processor.py", line 58, in transform_event
    transformed_event = self.get_transformed_event(event)
  File "/openedx/venv/lib/python3.8/site-packages/event_routing_backends/processors/mixins/base_transformer_processor.py", line 100, in get_transformed_event
    return self.registry.get_transformer(event).transform()
  File "/openedx/venv/lib/python3.8/site-packages/event_routing_backends/processors/xapi/transformer.py", line 45, in transform
    transformed_props = super().transform()
  File "/openedx/venv/lib/python3.8/site-packages/event_routing_backends/processors/mixins/base_transformer.py", line 97, in transform
    self.base_transform()
  File "/openedx/venv/lib/python3.8/site-packages/event_routing_backends/processors/xapi/transformer.py", line 53, in base_transform
    actor = self.get_actor()
  File "/openedx/venv/lib/python3.8/site-packages/event_routing_backends/processors/xapi/transformer.py", line 82, in get_actor
    user_uuid = get_anonymous_user_id(self.extract_username_or_userid(), 'XAPI')
  File "/openedx/venv/lib/python3.8/site-packages/event_routing_backends/helpers.py", line 66, in get_anonymous_user_id
    type_name = getattr(ExternalIdType, external_type)
AttributeError: type object 'ExternalIdType' has no attribute 'XAPI'
```
